In [77]:
import numpy as np
import pandas as pd

In [78]:
from sklearn.preprocessing import MinMaxScaler

In [79]:
data=pd.read_csv('VegetFood.csv')

In [80]:
data.head(3)

,ID,نام غذا,مواد اولیه,دستور,کالری برای یک نفر,سریع,لینک,وعده غذایی,نوع رژیم گیاهخواری,تعداد نفرات,کشور,کربوهیدرات,چربی,عکس
0,1,سوسیس گیاهی,سوسیس گیاهی/دو قوطی کبریت\nگوجه گیلاسی/پنج عدد...,-سوسیس گیاهی را سرخ کنید.\n-قارچ را تفت دهید.,400.0,1.0,https://boshghabesabz.com/vegan-sausage/,صبحانه,وگان,1,ایران,NaN,NaN,https://www.parsine.com/files/fa/news/1397/4/9...
1,2,باقلا خشکابیج با برنج قهوه ای,لوبیا چشم بلبلی/یک پیمانه\nسیر/پنج حبه\nزردچوب...,-لوبیا چشم بلبلی را خیس کنید و پوست بگیرید، می...,328.0,3.0,https://boshghabesabz.com/vegan-baghela-khoshk...,وعده اصلی,وگان,2,ایران,NaN,NaN,https://persianv.com/ashpazi/wp-content/upload...
2,3,حلیم شیر گیاهی,شیره افرا (یا شکر)/یک قاشق غذاخوری\nآب لیموترش...,-پیاز را نگینی خُرد کنید و با کمی روغن سرخ کنی...,500.0,7.0,https://boshghabesabz.com/vegan-milk-halim/,صبحانه,وگان,2,ایران,NaN,NaN,https://www.beytoote.com/images/stories/food/f...

In [81]:
data.drop(['دستور','لینک','عکس','چربی','کربوهیدرات','تعداد نفرات','سریع','نوع رژیم گیاهخواری'],axis=1,inplace=True)

In [82]:
data.head(2)

,ID,نام غذا,مواد اولیه,کالری برای یک نفر,وعده غذایی,کشور
0,1,سوسیس گیاهی,سوسیس گیاهی/دو قوطی کبریت\nگوجه گیلاسی/پنج عدد...,400.0,صبحانه,ایران
1,2,باقلا خشکابیج با برنج قهوه ای,لوبیا چشم بلبلی/یک پیمانه\nسیر/پنج حبه\nزردچوب...,328.0,وعده اصلی,ایران

In [83]:
d = data['مواد اولیه'].str.rsplit("\n")

In [84]:
for i in range(len(d)):
    for j in range(len(d[i])):
        d[i][j]=d[i][j].split("/")[0]

In [85]:
ingredients={
    'rice':['برنج'],
    'flour':['آرد','پودر ذرت','پودر سبوس جو','پودر سوخاری'],
    'other':['سیب زمینی','هویج'],
    'beetroot':['شلغم','چغندر','لبو'],
    'mushroom':['قارچ'],
    'meat':['کالباس','میت','سوسیس'],
    'bellpepper':['فلفل دلمه'],
    'pepper':['فلفل تازه','فلفل سبز','فلفل قرمز هندی','فلفل چیلی سبز'],
    'squash':['کدو'],
    'chocolate':['کاکائو','شکلات'],
    'sauce':['سس سویا','سس مایونز','سس چیلی','سس کنجد','سس کچاپ','سس گوجه','سویا سس'],
    'egg':['تخم مرغ'],
    'garlic':['سیر'],
    'dairy':['توفو','شیر','شیر کنجد','شیر سویا','شیر نارگیل','شیر بادام','ماست','کشک','پنیر سویا','پنیر'],
    'legume':['باقلا','حبوبات','لوبیا','لپه','سیاه دانه','نخود','عدس'],
    'oil':['روغن زیتون','روغن کنجد','روغن','کره'],
    'greens':['لوبیا سبز','بامیه','سبزیجات','اسفناج','برگ نعناع','تربچه','جعفری','جلبک دریایی','روکولا','ریحان','نعناع','زیتون','سبزی','گشنیز','کاهو','پیازچه','شنبلیله','شوید','کرفس','کلم','واسابی','آمارانت'],
    'tomato':['رب گوجه','گوجه'],
    'eggplant':['بادمجان'],
    'nuts':['آجیل','تخم آفتابگردان','تخم شربتی','تخم چیا','تخم کتان','تخم کدو','تخم گشنیز','دانه خردل','دانه چیا','دانه کنف','فندق','مغزیجات','پسته','گردو','بادام','کنجد'],
    'noodle':['رشته','ورمیشل','پاستا','نودل'],
    'bread':['نون','نان'],
    'grain':['بلغور','جو','جوانه','جوانه آلفا','جوانه شبدر','جوانه ماش','سویا','گندم','ذرت','گیاهک گندم','کورن فلکس','کینوا'],
    'fruits':['آناناس','آووکادو','به','توت فرنگی','هندوانه','گلابی','گریپ فروت','کیوی','پرتقال','نارگیل','موز','سیب','خیار','هندونه','تمشک','توت'],
    'sweetener':['خرما','مربا','شیرین کننده','افرا','شیره','شکر','عسل','شهد','کشمش','گل محمدی','هل','گلاب','مویز'],
    'sour':['آبغوره','آلبالو','آلو','بالزامیک','ترشی','تمرهندی','دانه انار ترش','آلوچه','رب انار','زرشک','سرکه','سبزی ترش واش','قیصی','نارنج','لیمو','خیار شور','خیارشور','انار'],
    'spices':['کاری','سماق','پودر آویشن','آگار','ادویه','زعتر','زردچوبه','زعفران','زنجبیل','نمک','اورگانو','زیره','فلفل','گلپر','پودر کاری','دارچین','ماسالا','پاپریکا','نعناع','پودر پونه','پودر پیاز','پودر گوجه فرنگی','آویشن'],
    
}

In [86]:
for k in range(len(d)):
    for i in range(len(d[k])-1,-1,-1):
        for j in ingredients.keys():
            for x in ingredients[j]:
                if x in d[k][i]:
                    d[k][i]=j
        if d[k][i] not in ingredients.keys():
            del d[k][i]

In [87]:
for i in range(d.shape[0]):
    data['مواد اولیه'][i]=d[i]

C:\Users\manoto\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [88]:
icm=data.copy()
for index, row in data.iterrows():
    for ingred in row['مواد اولیه']:
        icm.at[index, ingred] = 1
icm=icm.fillna(0)
icm.drop(['نام غذا','مواد اولیه'],axis=1,inplace=True)
icm.rename(columns={'کالری برای یک نفر':'calorie',
                   'وعده غذایی':'meal',
                   'کشور':'region'},inplace=True)

In [89]:
icm.head(2)

,ID,calorie,meal,region,meat,tomato,mushroom,greens,nuts,oil,...,pepper,sweetener,eggplant,sauce,bellpepper,squash,chocolate,noodle,beetroot,egg
0,1,400.0,صبحانه,ایران,1.0,1.0,1.0,1.0,1.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,2,328.0,وعده اصلی,ایران,0.0,0.0,0.0,1.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [92]:
icm=pd.get_dummies(icm,columns=['region','meal'] , drop_first=False)

In [97]:
scaler = MinMaxScaler()
icm['calorie']=scaler.fit_transform(icm[['calorie']])

In [98]:
icm.head(2)

,ID,calorie,meat,tomato,mushroom,greens,nuts,oil,legume,garlic,...,meal_اسموتی,meal_دسر,meal_سالاد,meal_ساندویچ,meal_سس,meal_سوپ,meal_صبحانه,meal_فست فود,meal_وعده اصلی,meal_کیک
0,1,0.101942,1.0,1.0,1.0,1.0,1.0,1.0,0.0,0.0,...,0,0,0,0,0,0,1,0,0,0
1,2,0.081382,0.0,0.0,0.0,1.0,0.0,1.0,1.0,1.0,...,0,0,0,0,0,0,0,0,1,0

## testing a user

In [99]:
random_user_1=[
{'id':6,'point':1},
{'id':5,'point':1},
{'id':151,'point':1},
{'id':3,'point':-1},
{'id':15,'point':-1},
{'id':17,'point':-1},
]
random_user_1= pd.DataFrame(random_user_1)

In [100]:
pd.merge(data,random_user_1, how='inner', left_on = 'ID', right_on = 'id').drop('id',axis=1)

,ID,نام غذا,مواد اولیه,کالری برای یک نفر,وعده غذایی,کشور,point
0,3,حلیم شیر گیاهی,"[dairy, sour, greens, greens]",500.0,صبحانه,ایران,-1
1,5,نان تست چاودار به همراه کالباس گیاهی,"[bread, meat, greens, tomato]",300.0,صبحانه,ایران,1
2,6,لوبیاپلو گیاهی,"[legume, tomato, spices, meat, spices, spices,...",350.0,وعده اصلی,ایران,1
3,15,پنیر توفو,"[dairy, sour, garlic, spices]",465.0,صبحانه,ایران,-1
4,17,فرنی جو وگان,"[dairy, grain, grain, fruits, dairy]",375.0,صبحانه,ایران,-1
5,151,سوسیس بندری,"[meat, tomato, spices]",376.0,ساندویچ,ایران,1

In [101]:
userfeature=icm[icm['ID'].isin(random_user_1['id'].tolist())]
userfeature=userfeature.reset_index(drop=True).drop('ID',1)

In [102]:
userfeature

,calorie,meat,tomato,mushroom,greens,nuts,oil,legume,garlic,fruits,...,meal_اسموتی,meal_دسر,meal_سالاد,meal_ساندویچ,meal_سس,meal_سوپ,meal_صبحانه,meal_فست فود,meal_وعده اصلی,meal_کیک
0,0.130497,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0,0,0,0,0,0,1,0,0,0
1,0.073387,1.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0,0,0,0,0,0,1,0,0,0
2,0.087664,1.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,...,0,0,0,0,0,0,0,0,1,0
3,0.120503,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,...,0,0,0,0,0,0,1,0,0,0
4,0.094803,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,...,0,0,0,0,0,0,1,0,0,0
5,0.095089,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0,0,0,1,0,0,0,0,0,0

In [103]:
userProfile=userfeature.transpose().dot(random_user_1['point'])

In [104]:
pd.DataFrame(userProfile)

                       0
calorie        -0.018846
meat            1.000000
tomato          1.000000
mushroom        0.000000
greens          2.000000
nuts            0.000000
oil             1.000000
legume          1.000000
garlic         -1.000000
fruits         -1.000000
spices         -1.000000
rice            1.000000
dairy          -1.000000
sour            0.000000
bread           1.000000
other           1.000000
grain          -1.000000
flour           0.000000
pepper          0.000000
sweetener       0.000000
eggplant        0.000000
sauce           0.000000
bellpepper      0.000000
squash          0.000000
chocolate       0.000000
noodle          0.000000
beetroot        0.000000
egg             0.000000
region_ایران    0.000000
meal_آبمیوه     0.000000
meal_آش         0.000000
meal_اسموتی     0.000000
meal_دسر        0.000000
meal_سالاد      0.000000
meal_ساندویچ   -1.000000
meal_سس         0.000000
meal_سوپ        0.000000
meal_صبحانه     0.000000
meal_فست فود    0.000000
meal_وعده اصلی  1.000000
meal_کیک        0.000000

In [105]:
recommendation=(((icm.drop(icm[icm['ID'].isin(random_user_1['id'].tolist())].index).set_index('ID')*userProfile).sum(1)/(userProfile.sum())).sort_values(ascending=False)).reset_index(drop=False)

In [106]:
recommendation.head(2)

   ID         0
0   4  1.506855
1  27  1.255665

In [107]:
data.head(2)

,ID,نام غذا,مواد اولیه,کالری برای یک نفر,وعده غذایی,کشور
0,1,سوسیس گیاهی,"[meat, tomato, mushroom, greens, nuts, oil]",400.0,صبحانه,ایران
1,2,باقلا خشکابیج با برنج قهوه ای,"[legume, garlic, fruits, spices, spices, green...",328.0,وعده اصلی,ایران

In [108]:
recommended_item=data[data['ID'].isin(recommendation['ID'].head(5).tolist())]

In [109]:
recommended_item

,ID,نام غذا,مواد اولیه,کالری برای یک نفر,وعده غذایی,کشور
0,1,سوسیس گیاهی,"[meat, tomato, mushroom, greens, nuts, oil]",400.0,صبحانه,ایران
3,4,باقلا پلو با ته دیگ زعفرانی,"[meat, tomato, mushroom, greens, nuts, oil]",225.0,وعده اصلی,ایران
26,27,پلو مخلوط گیاهی,"[other, greens, spices, spices, spices, spices...",230.0,وعده اصلی,ایران
50,51,لوبیا پلو شیرازی,"[rice, legume, spices, greens, oil, other, flo...",400.0,وعده اصلی,ایران
58,59,خورشت لپه و سیب زمینی گیاهی,"[legume, tomato, tomato, sour, sour, other, oil]",353.0,وعده اصلی,ایران

In [110]:
recommended_item['نام غذا'].tolist()

['سوسیس گیاهی',
 'باقلا پلو با ته دیگ زعفرانی',
 'پلو مخلوط گیاهی',
 'لوبیا پلو شیرازی',
 'خورشت لپه و سیب زمینی گیاهی']